In [1]:
import pandas as pd
import numpy as np

 ## Numpy

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

In [3]:
arr=np.array([1,2,3])
type(arr)

numpy.ndarray

In [5]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr1=np.array([7,8,9])
arr1

array([7, 8, 9])

Nous pouvons effectuer des opérations mathématiques

In [7]:
arr+arr1

array([[ 8, 10, 12],
       [11, 13, 15]])

In [8]:
arr*arr1

array([[ 7, 16, 27],
       [28, 40, 54]])

In [37]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [38]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [9]:
arr1.shape

(3,)

In [10]:
arr.shape

(2, 3)

In [11]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
arr1.T

array([7, 8, 9])

In [13]:
# La transposition de arr1 se justifie : il y a une ligne trois colones.Donc cela ne change pas grand-chose.

In [14]:
arr1.T.shape

(3,)

In [15]:
arr.T.shape

(3, 2)

In [16]:
np.zeros

<function numpy.zeros>

In [19]:
arr2=np.zeros
arr2

<function numpy.zeros>

In [22]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
np.ones(shape=(3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Accédons aux éléments des arrays

In [30]:
arr[1,2]

6

In [32]:
arr[:, 1]

array([2, 5])

In [36]:
arr[:, 2]

array([3, 6])

In [33]:
arr[:, 0]

array([1, 4])

In [34]:
arr[0, :]

array([1, 2, 3])

In [35]:
arr[1, :]

array([4, 5, 6])

    Les ndarray sont des objets mutables 

In [50]:
arr[0, 0]= -1
arr

array([[-1,  1,  1],
       [ 4,  5,  6]])

In [54]:
arr[:, 0]=4
arr

array([[4, 1, 1],
       [4, 5, 6]])

    Nous pouvons sélectionner des éléments d'un ndarray suivant une condition

In [58]:
arr > 5

array([[False, False, False],
       [False, False,  True]])

In [60]:
 arr[arr>5]

array([6])

In [61]:
arr[arr>4]

array([5, 6])

On peut piocher dans des dizainesde fonctions dont Numpy dispose pour transformer les données

In [63]:
np.sum(arr)

21

In [64]:
np.sum(arr1)

24

In [65]:
np.sum(arr2)

<function numpy.zeros>

## axis=0
    Signifie que l'addition est réalisée suivant le dimension 0, ce sont donc les lignes qui sont additionnées .
## axis=1 
        Indique que ce sont les colonnes qui sont addictionnées.

In [68]:
np.sum(arr, axis=0)

array([8, 6, 7])

In [69]:
np.sum(arr, axis=1)

array([ 6, 15])

## Pandas

#### Ici l'objet le plus important est le DataFrame.(Tableau de données)

In [8]:
df= pd.DataFrame({'name':['Anna','Gill','Anauld','Ruth','Nathan'],'Age':[12,15,17,21,18],'height':[1.50,1.85,1.59,1.62,1.64]})

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df

name  Age  height
0    Anna   12    1.50
1    Gill   15    1.85
2  Anauld   17    1.59
3    Ruth   21    1.62
4  Nathan   18    1.64

In [5]:
df.head()

name  Age  height
0    Anna   12    1.50
1    Gill   15    1.85
2  Anauld   17    1.59
3    Ruth   21    1.62
4  Nathan   18    1.64

    Le df.head() affiche les 5 premiers du DataFrame, mais puisque nous avons 5 ici cela affiche aisni. Si c'était plusque 5 on aurait bien faire les remarques

In [6]:
df.tail()

name  Age  height
0    Anna   12    1.50
1    Gill   15    1.85
2  Anauld   17    1.59
3    Ruth   21    1.62
4  Nathan   18    1.64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    5 non-null      object 
 1   Age     5 non-null      int64  
 2   height  5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes


In [8]:
df.describe()

Age    height
count   5.000000  5.000000
mean   16.600000  1.640000
std     3.361547  0.129035
min    12.000000  1.500000
25%    15.000000  1.590000
50%    17.000000  1.620000
75%    18.000000  1.640000
max    21.000000  1.850000

In [9]:
df.shape

(5, 3)

In [10]:
df.index

RangeIndex(start=0, stop=5, step=1)

On remarque que l'indice numérique déarre souvent par 0. Nous povons définir un index plus interréssant en utilisant la colonne name par exemple

In [11]:
df= df.set_index("name")
df

Age  height
name               
Anna     12    1.50
Gill     15    1.85
Anauld   17    1.59
Ruth     21    1.62
Nathan   18    1.64

In [12]:
df.columns

Index(['Age', 'height'], dtype='object')

#### On peut indexer le tableau avec les méthodes loc et iloc

In [13]:
df.loc["Anna"]

Age       12.0
height     1.5
Name: Anna, dtype: float64

In [14]:
df.iloc[1,1]

1.85

Je veux avoir l'age de Anauld et sa taille

In [15]:
df.iloc[2,:]

Age       17.00
height     1.59
Name: Anauld, dtype: float64

In [16]:
df.loc["Anauld"]

Age       17.00
height     1.59
Name: Anauld, dtype: float64

In [17]:
df.iloc[[1,2],[0,1]]

Age  height
name               
Gill     15    1.85
Anauld   17    1.59

J'aimerais afficher le nom de ceux qui ont moins de 15ans

In [18]:
df.iloc[:,0]<15

name
Anna       True
Gill      False
Anauld    False
Ruth      False
Nathan    False
Name: Age, dtype: bool

J'aimerais afficher le nom de ceux qui ont moins de 18ans

In [19]:
df.iloc[:,0]<18

name
Anna       True
Gill       True
Anauld     True
Ruth      False
Nathan    False
Name: Age, dtype: bool

In [20]:
df.iloc[:,0]<15

name
Anna       True
Gill      False
Anauld    False
Ruth      False
Nathan    False
Name: Age, dtype: bool

I'm reashing for the persons who have the normal height.

In [21]:
normal_height=1.60
df.iloc[:,1] >= normal_height

name
Anna      False
Gill       True
Anauld    False
Ruth       True
Nathan     True
Name: height, dtype: bool

Anna & Anauld don't have a normal height.

 #### Selection d'une colonne entière pour l'utiliser ou la modifier 

In [5]:
df['Age']

0    12
1    15
2    17
3    21
4    18
Name: Age, dtype: int64

In [15]:
df['Age2']= df['Age']+2
df['Age2']

0    14
1    17
2    19
3    23
4    20
Name: Age2, dtype: int64

In [7]:
df['Age']= df['Age']+2
df.head()

name  Age  height  Age2
0    Anna   14    1.50    14
1    Gill   17    1.85    17
2  Anauld   19    1.59    19
3    Ruth   23    1.62    23
4  Nathan   20    1.64    20

#### On peut ajouter des colonnes 

In [11]:
df['Age_plus_10']=df['Age']+10
df.head()

name  Age  height  Age_plus_10
0    Anna   12    1.50           22
1    Gill   15    1.85           25
2  Anauld   17    1.59           27
3    Ruth   21    1.62           31
4  Nathan   18    1.64           28

#### On peut aussi faire les sommes des colonnes comme dans numpy

In [12]:
df['height'].sum()

8.200000000000001

In [13]:
df['Age'].sum()

83

In [16]:
df['Age2'].sum()

93

In [24]:
df['height'].value_counts()

height
1.50    1
1.85    1
1.59    1
1.62    1
1.64    1
Name: count, dtype: int64

In [25]:
df['Age'].value_counts()

Age
12    1
15    1
17    1
21    1
18    1
Name: count, dtype: int64

#### On peut facilement lire & écrire das fichiers (.csv par exemple) avec pandas

In [18]:
myfich=pd.read_csv("/home/vini/Downloads/Telegram Desktop/Customer.csv")
myfich

age  pages first_item_prize gender  ReBuy  News_click country revenue
0     41.0    6.0             28.0    Fem  False         4.0   China     113
1     34.0    4.0             15.5    Fem   True         2.0   China      36
2     38.0    5.0                ?    Fem  False         7.0   China     111
3     20.0    1.0             44.0    Fem  False         2.0   China      71
4     39.0   10.0             10.0    Fem   True         4.0   China      80
...    ...    ...              ...    ...    ...         ...     ...     ...
9995  49.0    8.0             44.0   Masc  False         4.0  Taiwan     254
9996  32.0    5.0             42.0   Masc  False         1.0  Taiwan      82
9997  47.0    8.0             15.5    Fem   True         3.0  Taiwan     117
9998  42.0    7.0             42.0    Fem  False         2.0  Taiwan      70
9999  41.0    5.0             42.0    Fem  False         2.0  Taiwan     107

[10000 rows x 8 columns]

In [19]:
myfich.describe()

age         pages    News_click
count  10000.000000  10000.000000  10000.000000
mean      37.431400      5.995000      4.412000
std        9.490474      2.438559      2.418231
min       18.000000      1.000000      0.000000
25%       31.000000      5.000000      3.000000
50%       37.000000      6.000000      4.000000
75%       43.000000      7.000000      6.000000
max       79.000000     14.000000     10.000000

#### On peut compter le nombre d'éléments identique dans une colonne avec la méthode value_counts. 
Cette méthode est disponible pour les objets de type "Séries" qui représentent en fait les colonnes.

In [21]:
myfich["country"].value_counts()

country
China             200
Morocco           200
Ukraine           200
Tanzania          200
Kenya             200
Argentina         200
Algeria           200
Poland            200
Sudan             200
Uganda            200
Canada            200
Iraq              200
Peru              200
India             200
Uzbekistan        200
Malaysia          200
Saudi Arabia      200
Venezuela         200
Nepal             200
Afghanistan       200
Yemen             200
Ghana             200
Mozambique        200
Australia         200
Spain             200
Colombia          200
South Korea       200
South Africa      200
United States     200
Indonesia         200
Brazil            200
Pakistan          200
Nigeria           200
Bangladesh        200
Russia            200
Japan             200
Mexico            200
Philippines       200
Vietnam           200
Ethiopia          200
Egypt             200
Germany           200
Iran              200
Turkey            200
Thailand          200
Fr

#### On peut  grouper les données et agréger les groupes obtenus à l'aide de fonctions.

In [27]:
myfich.groupby("gender").agg({'age':['max','min'],'ReBuy':["mean","std"]})

age           ReBuy          
         max   min      mean       std
gender                                
Fem     79.0  18.0  0.282382  0.450191
Masc    79.0  18.0  0.274693  0.446432

#### Je décide de vérifier si ce sont des femmes 

In [28]:
myfich["gender"]=="Fem"

0        True
1        True
2        True
3        True
4        True
        ...  
9995    False
9996    False
9997     True
9998     True
9999     True
Name: gender, Length: 10000, dtype: bool

In [3]:
!type myfich.csv

/bin/bash: line 1: type: myfich.csv: not found


## Matplotlib

In [4]:
import matplotlib.pyplot as plt

### Matplotlib a un mode similaire à celui de Matlab, on enchaîne juste des appels à des fonctions pour réaliser des actions sur le même objet.