In [1]:
import numpy as np

In [2]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
array1= np.ones(4)
array1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
array2= np.ones((2,3))
array2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
array3= np.zeros(3)
array3

array([0., 0., 0.])

In [17]:
array4= np.eye(4)
array4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Nous avons constaté qu'avec np.eye() & np.identity() on peut avoir des des matrices/array avec même comportement.